//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Xml;


/// <summary>
/// A sample XML Reader
/// </summary>
/// <remarks>
/// 	created by - Devendra Tewari
/// 	created on - 5/4/2002 19:22:46
/// </remarks>
public class TestXMLReader : object {
	
	/// <summary>
	/// Default constructor - initializes all fields to default values
	/// </summary>
	public TestXMLReader() {
	}
	
	public static void Main() {
		XmlTextReader reader = new
		      XmlTextReader("test.xml");
		while (reader.Read()) {
			if (reader.NodeType == XmlNodeType.Element) {
				System.Console.WriteLine("Found Element: " + reader.Name);
				if (reader.HasAttributes) {
					while (reader.MoveToNextAttribute())  {
						System.Console.WriteLine(
						"Found Attribute: " + reader.Name);
					}
				}
			}
		}
		// Make sure you close the stream to prevent file locking
		reader.Close();
	}
}
